### PR TITLE
Allow colors in output

### PR DESCRIPTION
**Pull request by kayoub5**

### CODE REVIEW

**Comment by rarkins** [comment]
@kayoub5 I had expected these "ticks" to be coloured green:

image

Can you work out what we need to do in order to get that working?

**Comment by kayoub5** [comment]
@rarkins you can play with `chalk` module to experiment with colors

**Comment by rarkins** [comment]
@kayoub5 I expected they were already generated in colour by the log-symbols package actually

**Comment by kayoub5** [comment]
that's fixed, log-symbols uses chalk, chalk detected that we were using CI so disabled colors, and force enabled them in make

**Pull request merged**
